### ISSUE TITLE
`@icon` is huge

### ISSUE THREAD

**Issue by Martii** [Webbeh/UserScript_PokemonTrash#1]
How about being nice to your end users and scale back [your `@icon`](/Webbeh/UserScript_PokemonTrash/blob/6727b9cb43da051bd9df8d8cb6b07c61f65d6a93/pt.user.js#L10) please. 

900px by 900px is a bit much at ~706.6KiB ... most .user.js engines maximum is around 48px by 48px. Having overly large, unnecessary, assets can be a good way to get your script down voted.

EDIT: This size is a bit more reasonable for the managers at ~6.04KiB:
![14754800337245miaouss48](https://user-images.githubusercontent.com/114709/33551111-8dab5142-d8ad-11e7-8566-2a8a9bb8a5fe.png)

as compared to this *(fitted by CSS as well so it's even bigger)*:
![http://www.plixup.com/pics_core3/14754800337245miaouss.png](http://www.plixup.com/pics_core3/14754800337245miaouss.png)

Thanks
OUJS Admin

---

**EDIT**:
* We've implemented a new limitation so if you want to be able to update your script, this includes using the webhook, you'll need to down scale it.

Thanks,
OUJS Staff

**Comment by Webbeh** [comment]
Thanks.

Changed.
